config/routes.rb
Rails.application.routes.draw do
	
	get 'home' => 'home#index'
	
	get 'about' => 'about#index'
	
	get 'blog' => 'blog#index'
	
	resources :articles do
	  resources :comments
	end
    
    resources :messages
	
	get 'contact' => 'contact#index'
	
  	root 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments, dependent: :destroy
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/message.rb
class Message < ApplicationRecord

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	http_basic_authenticate_with name: "admin", password: "secret", except: [:index, :show]
	
def index
    @articles = Article.order('id DESC')
  end
 
  def show
    @article = Article.find(params[:id])	  
	@articles = Article.order('id DESC')
  end
 
  def new
    @article = Article.new
  end
 
  def edit
    @article = Article.find(params[:id])
  end
 
  def create
    @article = Article.new(article_params)
 
    if @article.save
      redirect_to @article
    else
      render 'new'
    end
  end
 
  def update
    @article = Article.find(params[:id])
 
    if @article.update(article_params)
      redirect_to @article
    else
      render 'edit'
    end
  end
 
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
 
    redirect_to articles_path
  end
 
  private
    def article_params
      params.require(:article).permit(:title, :text)
    end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
http_basic_authenticate_with name: "admin", password: "secret", except: [:index, :show]
	
	
	def index
		@articles = Article.order('id DESC')

	  end

	  def show
		@article = Article.find(params[:id])
	  end

	  def new
		@article = Article.new
	  end

	  def edit
		@article = Article.find(params[:id])
	  end

	  def create
		@article = Article.new(article_params)

		if @article.save
		  redirect_to @article
		else
		  render 'new'
		end
	  end

	  def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
		  redirect_to @article
		else
		  render 'edit'
		end
	  end

	  def destroy
		@article = Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	  end

	  private
		def article_params
		  params.require(:article).permit(:title, :text)
		end
	end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
http_basic_authenticate_with name: "admin", password: "secret", except: [:index, :show]
	  

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end
 
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end
	
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
http_basic_authenticate_with name: "admin", password: "secret", except: [:create]
    
    def index
        @messages = Message.all
    end
    
    def create
        @message = Message.create(message_params)
    
        if @message.save
            message = { notice: "Message sent!"}
        end
        
        redirect_to contact_path, flash: message
    end
    
    def destroy
    @message = Message.find(params[:id])
    @message.destroy
 
    redirect_to messages_path
  end
	
  private
    def message_params
      params.require(:message).permit(:title, :text)
    end

    
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-error"
      when :alert
        "alert-block"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/carousel_helper.rb
# app/helpers/carousel_helper.rb

module CarouselHelper
  def carousel_for(images)
    Carousel.new(self, images).html
  end

  class Carousel
    def initialize(view, images)
      @view, @images = view, images
	@uid = SecureRandom.hex(6)
    end
	  
	attr_accessor :uid

    def html
      content = view.safe_join([indicators, slides, controls])
      view.content_tag(:div, content, class: 'carousel slide')
    end

    private

    attr_accessor :view, :images
    delegate :link_to, :content_tag, :image_tag, :safe_join, to: :view

     def indicators
      items = images.count.times.map { |index| indicator_tag(index) }
      content_tag(:ol, safe_join(items), class: 'carousel-indicators')
    end

    def indicator_tag(index)
      options = {
        class: (index.zero? ? 'active' : ''),
        data: { 
          target: uid, 
          slide_to: index 
        }
      }

      content_tag(:li, '', options)
    end

    def slides
      items = images.map.with_index { |image, index| slide_tag(image, index.zero?) }
      content_tag(:div, safe_join(items), class: 'carousel-inner')
    end

    def slide_tag(image, is_active)
      options = {
        class: (is_active ? 'item active' : 'item'),
      }

      content_tag(:div, image_tag(image), options)
    end

    def controls
      safe_join([control_tag('left'), control_tag('right')])
    end

    def control_tag(direction)
      options = {
        class: "#{direction} carousel-control",
        data: { slide: direction == 'left' ? 'prev' : 'next' }
      }

      icon = content_tag(:i, nil, class: "glyphicon glyphicon-chevron-#{direction}")
      control = link_to(icon, "##{uid}", options)
    end
	
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/articles/edit.html.erb
<div class="col-lg-12">
	<div class="header">
		<div class="logo"><%= image_tag "cat-logo.svg"%></div>
	</div>
</div>

<div class="col-lg-12">
<div class="navbar navbar-default">
         <div class="navbar-header">
			 <a class="navbar-brand" href="#"></a>
        </div>
        <ul class="nav navbar-nav">
  	<li role="presentation"><%= link_to 'HOME', home_path %></li>
  	<li role="presentation"><%= link_to 'ABOUT', about_path %></li>
  	<li role="presentation" class="active"><%= link_to 'BLOG', blog_path %></li>
	<li role="presentation"><%= link_to 'CONTACT', contact_path %></li>
	<li class="divider-vertical"></li>
	<form class="navbar-form navbar-right" role="search">
			<button type="submit" class="btn btn-default"><%= link_to 'New Post', new_article_path %></button>
			</form>
	</ul>
	</div>
	

  	  <div class="container">	
      <div class="row">
        <div class="col-lg-8">

<h1>Edit article</h1>
 
<%= form_for(@article) do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title, size: "100%" %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text, size: "100%x10%" %>
  </p>
 
  <p>   
    <%= f.submit 'Update article', :class => 'btn btn-primary'%>
    <a href="<%= blog_path %>"><button type="button" class="btn btn-primary">Back</button></a>
    <% end %>
  </p>			
		  </div>
		  </div>
	</div>
	
			
<div class="panel panel-default">
<div class="panel-footer">
	  
	  <p>© <%= Date.today.year %> Marta Stanke</p>
</div>
</div>

</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

app/views/articles/index.html.erb
<div class="col-lg-12">
	<div class="header">
		<div class="logo"><%= image_tag "cat-logo.svg"%></div>
	</div>
</div>

<div class="col-lg-12">
<div class="navbar navbar-default">
         <div class="navbar-header">
			 <a class="navbar-brand" href="#"></a>
        </div>
        <ul class="nav navbar-nav">
  	<li role="presentation"><%= link_to 'HOME', home_path %></li>
  	<li role="presentation"><%= link_to 'ABOUT', about_path %></li>
  	<li role="presentation" class="active"><%= link_to 'BLOG', blog_path %></li>
	<li role="presentation"><%= link_to 'CONTACT', contact_path %></li>
	<li class="divider-vertical"></li>
	</ul>
	</div>
	

  	  <div class="container">	
      <div class="row">
        <div class="col-lg-12">
            <h3>This is a test site where I explore new layout ideas</h3>
            
            <ul class="ch-grid">
	<li>
	<div class="ch-item">				
		<div class="ch-info">
			<div class="ch-info-front ch-img-1"></div>
			<div class="ch-info-back">
				<h3>Poland</h3>
				<p> <a href="http://drbl.in/eAoj">View gallery</a></p>
			</div>	
		</div>
	</div>
</li>
	<li>
	<div class="ch-item">				
		<div class="ch-info">
			<div class="ch-info-front ch-img-2"></div>
			<div class="ch-info-back">
				<h3>Food</h3>
				<p> <a href="http://drbl.in/eAoj">View gallery</a></p>
			</div>	
		</div>
	</div>
</li>
	<li>
	<div class="ch-item">				
		<div class="ch-info">
			<div class="ch-info-front ch-img-3"></div>
			<div class="ch-info-back">
				<h3>Hong Kong</h3>
				<p> <a href="http://drbl.in/eAoj">View gallery</a></p>
			</div>	
		</div>
	</div>
</li>
</ul>
            
            <h3>Circular Images, Equal Height and Width</h3>  
<ul class="list-inline gallery">   
<li><img class="img-circle zoom" src="http://lorempixel.com/110/110/abstract/2"></li>    
<li><img class="img-circle zoom" src="http://lorempixel.com/110/110/abstract/3"></li>    
<li><img class="img-circle zoom" src="http://lorempixel.com/110/110/abstract/4"></li>  
</ul>
      </div>
          </div>
    
	
<div class="panel panel-default">
<div class="panel-footer">
	  
	  <p>© <%= Date.today.year %> Marta Stanke</p>
</div>
</div>

    </div>	
</div>
	
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

app/views/articles/new.html.erb
<div class="col-lg-12">
	<div class="header">
		<div class="logo"><%= image_tag "cat-logo.svg"%></div>
	</div>
</div>

<div class="col-lg-12">
<div class="navbar navbar-default">
    <div class="container-fluid">
         <div class="navbar-header">
			 <a class="navbar-brand" href="#"></a>
        </div>
         <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
  	<li><%= link_to 'HOME', home_path %></li>
  	<li><%= link_to 'ABOUT', about_path %></li>
  	<li class="active"><%= link_to 'BLOG', blog_path %></li>
	<li><%= link_to 'CONTACT', contact_path %></li>
	<a href="<%= new_article_path %>"><button type="button" class="btn btn-default navbar-btn">New Article</button></a>
	</ul>
	</div>
    </div>
    </div>
	
	
 <div class="col-md-12"></div>
    <hr>

  	  <div class="container">	
      <div class="row">
        <div class="col-lg-12">
 <div class="new-article">
<%= form_for :article, url: articles_path do |f| %>
 
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@article.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @article.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  
	<div class="col-lg-12">
	<p>
    <%= f.label :title %><br>
    <%= f.text_field :title, size: "100%" %>
  </p>
			</div>
			
			<div class="col-lg-12">
              <p>
                <%= f.label :text %><br>
                <%= f.text_area :text, size: "100%x10%" %>
              </p>
			</div>
            
                <%= f.submit 'Submit', :class => 'btn btn-primary'%>
                <a href="<%= blog_path %>"><button type="button" class="btn btn-primary">Back</button></a>
            <% end %>
 		
		  </div>
	</div>
	</div>
    </div>
    
<div class="panel panel-default">
<div class="panel-footer">
	  
	  <p>© <%= Date.today.year %> Marta Stanke</p>
</div>
</div>

	
</div>
	
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

app/views/articles/show.html.erb
<div class="col-lg-12">
	<div class="header">
		<div class="logo"><%= image_tag "cat-logo.svg"%></div>
	</div>
</div>

<div class="col-lg-12">
<div class="navbar navbar-default">
    <div class="container-fluid">
         <div class="navbar-header">
			 <a class="navbar-brand" href="#"></a>
        </div>
         <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
  	<li><%= link_to 'HOME', home_path %></li>
  	<li><%= link_to 'ABOUT', about_path %></li>
  	<li class="active"><%= link_to 'BLOG', blog_path %></li>
	<li><%= link_to 'CONTACT', contact_path %></li>
	<a href="<%= new_article_path %>"><button type="button" class="btn btn-default navbar-btn">New Article</button></a>
	</ul>
	</div>
    </div>
    </div>
  	  <div class="container">	
      <div class="row">
          <div class="col-lg-8">

                <!-- Blog Post -->

                <!-- Title -->
                <h1><%= @article.title %></h1>

                <!-- Author -->
                <p class="lead">
                    by Marta
                </p>

                <hr>

                <!-- Date/Time -->
                <p><span class="glyphicon glyphicon-time"></span> Posted on <%= @article.created_at.strftime("%b %d, %Y, %H:%M") %> |<%= link_to ' Edit ', edit_article_path(@article) %> |<%= link_to ' Back ', blog_path %></p>

                <hr>
                <!-- Post Content -->
                <p class="lead"></p>
				<p class="article-text"><%= simple_format @article.text %></p>
                <hr>

                <!-- Blog Comments -->
			  
				<%= render @article.comments %>
			  
                <!-- Comments Form -->
                <div class="well">
                    <h2>Add a comment:</h2>
					<%= render 'comments/form' %>
                </div>

                <hr>

                <!-- Posted Comments -->
				
                <!-- Comment -->
					
               </div>
        
		  <!-- Blog Sidebar Widgets Column -->
            <div class="col-lg-4">
                 <div class="well">
			<div class="[ info-card ]">
					<%= image_tag "profile-pic.jpg", :style => "width: 100%" %>
					<div class="[ info-card-details ] animate">
						<div class="[ info-card-header ]">
							<h1> About the Blog </h1>
							<h3> and social links </h3>
						</div>
						<div class="[ info-card-detail ]">
							<!-- Description -->
							<p>Blog posts courtesy of WikiProject Women Scientists, a WikiProject dedicated to ensuring quality and coverage of biographies of women scientists. Women's contributions in areas such as science are severely underrepresented in Wikipedia's pages. Let's change that!</p>
								<div class="social">
								<%= link_to "http://www.facebook.com/marta.szatanke" do %>
								  <%= image_tag "social-icons/1498920409_facebook.svg" %>
								<% end %>

								<%= link_to "http://www.twitter.com/MartaStanke" do %>
								  <%= image_tag "social-icons/1498920466_twitter.svg" %>
								<% end %>

								<%= link_to "http://pl.pinterest.com/martastanke" do %>
								  <%= image_tag "social-icons/1498920405_pinterest.svg" %>
								<% end %>

								<%= link_to "http://www.linkedin.com/in/martastanke/" do %>
								  <%= image_tag "social-icons/1498920411_linkedin.svg" %>
								<% end %>

								<%= link_to "http://www.github.com/marstanke" do %>
								  <%= image_tag "social-icons/1498920397_github.svg" %>
								<% end %>
          						</div>
						</div>
					</div>
				</div>
                </div>
                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Recent posts</h4>
                    <div class="row">
                        <div class="col-lg-12">
                            <ul class="list-unstyled"> 
							 <% @articles.first(3).each do |article| %>
							<li><h5><%= article.title %> <small>| <%= article.created_at.strftime("%b %d, %Y") %>  |</small>
								<%= link_to 'Show', article_path(article) %></h5></li>
							<% end %>
							</ul>
                        </div>
                       
                    </div>
                    <!-- /.row -->
                </div>

            </div>
      </div>
      </div>


<div class="panel panel-default">
<div class="panel-footer">
	  
	  <p>© <%= Date.today.year %> Marta Stanke</p>
</div>
</div>

	
</div>
	
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

app/views/blog/index.html.erb
<div class="col-lg-12">
	<div class="header">
		<div class="logo"><%= image_tag "cat-logo.svg"%></div>
	</div>
</div>

<div class="col-lg-12">
<div class="navbar navbar-default">
    <div class="container-fluid">
         <div class="navbar-header">
			 <a class="navbar-brand" href="#"></a>
        </div>
         <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
  	<li><%= link_to 'HOME', home_path %></li>
  	<li><%= link_to 'ABOUT', about_path %></li>
  	<li class="active"><%= link_to 'BLOG', blog_path %></li>
	<li><%= link_to 'CONTACT', contact_path %></li>
	<a href="<%= new_article_path %>"><button type="button" class="btn btn-default navbar-btn">New Article</button></a>
	</ul>
	</div>
    </div>
    </div>

  	  <div class="container">	
      <div class="row">
        <div class="col-lg-8">
			<div class="category recent-posts">
				 <ul>
					<% @articles.each do |article| %>
					 
					<h1 role="presentation"><%= article.title %></h1>
					<!-- Author -->
					<p class="lead">
						by Marta</p>

					<!-- Date/Time -->
					<p><span class="glyphicon glyphicon-time"></span> <%= article.created_at.strftime("%b %d, %Y, %H:%M") %> | <%= link_to 'Show', article_path(article) %> |
					<%= link_to 'Edit', edit_article_path(article) %> |
					<%= link_to 'Destroy', article_path(article),
              			method: :delete,
						data: { confirm: 'Are you sure?' } %></p>
					 <hr>
					 <p class="lead"><%= h truncate(article.text, :length => 130, :separator => ' ') %></p>
					 
                <hr>
					<% end %>
				
				</ul>
			
			</div>
		  </div>
        
		  <div class="col-lg-4">
			 <div class="well">
			<div class="[ info-card ]">
					<%= image_tag "profile-pic.jpg", :style => "width: 100%" %>
					<div class="[ info-card-details ] animate">
						<div class="[ info-card-header ]">
							<h1> About the Blog </h1>
							<h3> and social links </h3>
						</div>
						<div class="[ info-card-detail ]">
							<!-- Description -->
							<p>Blog posts courtesy of WikiProject Women Scientists, a WikiProject dedicated to ensuring quality and coverage of biographies of women scientists. Women's contributions in areas such as science are severely underrepresented in Wikipedia's pages. Let's change that!</p>
								<div class="social">
								<%= link_to "http://www.facebook.com/marta.szatanke" do %>
								  <%= image_tag "social-icons/1498920409_facebook.svg" %>
								<% end %>

								<%= link_to "http://www.twitter.com/MartaStanke" do %>
								  <%= image_tag "social-icons/1498920466_twitter.svg" %>
								<% end %>

								<%= link_to "http://pl.pinterest.com/martastanke" do %>
								  <%= image_tag "social-icons/1498920405_pinterest.svg" %>
								<% end %>

								<%= link_to "http://www.linkedin.com/in/martastanke/" do %>
								  <%= image_tag "social-icons/1498920411_linkedin.svg" %>
								<% end %>

								<%= link_to "http://www.github.com/marstanke" do %>
								  <%= image_tag "social-icons/1498920397_github.svg" %>
								<% end %>
          						</div>
						</div>
					</div>
				</div>
                </div>
            <!-- Links Well -->
                <div class="well">
                    <h4>Recent Posts</h4>
                    <div class="row">
                        <div class="col-lg-12">
                            <ul class="list-unstyled">
                            <% @articles.first(3).each do |article| %>
							<li><h5><%= article.title %> <small>| <%= article.created_at.strftime("%b %d, %Y") %>  |</small>
								<%= link_to 'Show', article_path(article) %></h5></li>
							<% end %>
							</ul>
                        </div>
                        
                    </div>
                    <!-- /.row -->
                </div>
        </div>
      </div>
      </div>


<div class="panel panel-default">
<div class="panel-footer">
	  
	  <p>© <%= Date.today.year %> Marta Stanke</p>
</div>
</div>

	
</div>
	
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

app/views/comments/_comment.html.erb
<div class="media">
	<div class="media-body">
		<blockquote>
		<h4 class="media-heading"><%= comment.commenter %>
		<small><%= comment.body %></small></h4>
		<p>
  			<%= link_to 'Delete', [comment.article, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
		</p>
		</blockquote>
	</div>
</div>

app/views/comments/_form.html.erb
<%= form_for([@article, @article.comments.build]) do |f| %>
  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>
  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/contact/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/messages/_form.html.erb
<%= form_for @message do |f| %>
 
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

app/views/messages/index.html.erb
<div class="col-lg-12">
	<div class="header">
		<div class="logo"><%= image_tag "cat-logo.svg"%></div>
	</div>
</div>

<div class="col-lg-12">
<div class="navbar navbar-default">
         <div class="navbar-header">
			 <a class="navbar-brand" href="#"></a>
        </div>
        <ul class="nav navbar-nav">
  	<li role="presentation"><%= link_to 'HOME', home_path %></li>
  	<li role="presentation"><%= link_to 'ABOUT', about_path %></li>
  	<li role="presentation"><%= link_to 'BLOG', blog_path %></li>
	<li role="presentation" class="active"><%= link_to 'CONTACT', contact_path %></li>
	<li class="divider-vertical"></li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Follow me! <span class="caret"></span></a>
          <ul class="dropdown-menu">
			<%= link_to "http://www.facebook.com/marta.szatanke" do %>
            <%= image_tag "social-icons/1498920409_facebook.svg" %>
            <% end %>

            <%= link_to "http://www.twitter.com/MartaStanke" do %>
            <%= image_tag "social-icons/1498920466_twitter.svg" %>
            <% end %>

            <%= link_to "http://pl.pinterest.com/martastanke" do %>
            <%= image_tag "social-icons/1498920405_pinterest.svg" %>
            <% end %>

            <%= link_to "http://www.linkedin.com/in/martastanke/" do %>
            <%= image_tag "social-icons/1498920411_linkedin.svg" %>
            <% end %>
              
            <%= link_to "http://www.github.com/marstanke" do %>
            <%= image_tag "social-icons/1498920397_github.svg" %>
			<% end %>
          </ul>
		</ul>
	</div>
	
	<div class="col-md-12">
        	</div>
    <hr>

<div class="col-lg-12">
	<div class="container">	
      <div class="row">
        <div class="col-lg-8">
			<div class="category recent-posts">

<h1>Messages from fans</h1>
 
<ul class="messages">
    <% @messages.each do |message| %>
   
    <h4><small>Sent: <%= message.created_at.strftime("%b %d, %Y, %H:%M") %> <%= link_to 'Destroy', message_path(message),
              			method: :delete,
						data: { confirm: 'Are you sure?' } %></small></h4>
	<h4 class="media-heading">Author: <%= message.title %></h4>
    <p>Message: <%= message.text %></p>
    <% end %>
</ul>
            </div>
          </div>
        </div>
    </div>
                
<div class="panel panel-default">
<div class="panel-footer">
	  
	  <p>© <%= Date.today.year %> Marta Stanke</p>
</div>
</div>
</div>
</div>
	
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>